# Makefile for the APQ_Provider
#
# @author Marcelo Coraça de Freitas <marcelo@kow.com.br> 

ifndef ($(PREFIX))
	PREFIX=/usr/local
endif
INCLUDE_PREFIX=$(PREFIX)/include/apqprovider-postgresql
LIB_PREFIX=$(PREFIX)/lib
GPR_PREFIX=$(LIB_PREFIX)/gnat


projectFile="apq_provider-postgresql.gpr"


libs:
	gnatmake -P ${projectFile}

all: libs


clean:
	gnatclean -P ${projectFile}
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"
